// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$180 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$180() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_RenderDrawRectsF",
        constants$6.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_RenderFillRectF",
        constants$6.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_RenderFillRectsF",
        constants$6.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_RenderCopyF",
        constants$5.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_RenderCopyExF",
        constants$178.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_RenderGeometry",
        constants$172.const$3
    );
}


