// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$55 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$55() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_BYTE
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_SetSurfaceAlphaMod",
        constants$55.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_GetSurfaceAlphaMod",
        constants$8.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_SetSurfaceBlendMode",
        constants$28.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_GetSurfaceBlendMode",
        constants$8.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_SetClipRect",
        constants$8.const$2
    );
}


