// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$174 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$174() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_RenderGetLogicalSize",
        constants$59.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_RenderSetIntegerScale",
        constants$34.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_RenderGetIntegerScale",
        constants$18.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_RenderSetViewport",
        constants$6.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_RenderGetViewport",
        constants$67.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_RenderSetClipRect",
        constants$6.const$4
    );
}


