// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$154 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$154() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_SetEventFilter",
        constants$56.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(SDL_GetEventFilter$filter.class, "apply", constants$8.const$2);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_GetEventFilter",
        constants$8.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(SDL_AddEventWatch$filter.class, "apply", constants$8.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_AddEventWatch",
        constants$56.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(SDL_DelEventWatch$filter.class, "apply", constants$8.const$2);
}


