// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$78 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$78() {}
    static final VarHandle const$0 = constants$77.const$3.varHandle(MemoryLayout.PathElement.groupElement("mod"));
    static final VarHandle const$1 = constants$77.const$3.varHandle(MemoryLayout.PathElement.groupElement("unused"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_GetKeyboardFocus",
        constants$0.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_GetKeyboardState",
        constants$2.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_ResetKeyboard",
        constants$26.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_GetModState",
        constants$1.const$4
    );
}


