// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$167 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$167() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_DelEventWatch",
        constants$67.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(SDL_FilterEvents$filter.class, "apply", constants$6.const$4);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_FilterEvents",
        constants$67.const$4
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_BYTE,
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_EventState",
        constants$167.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_RegisterEvents",
        constants$8.const$0
    );
}


