// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$18 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$18() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_atan",
        constants$17.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_atanf",
        constants$17.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_DOUBLE,
        JAVA_DOUBLE,
        JAVA_DOUBLE
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_atan2",
        constants$18.const$2
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(JAVA_FLOAT,
        JAVA_FLOAT,
        JAVA_FLOAT
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_atan2f",
        constants$18.const$4
    );
}


