// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$166 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$166() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$3.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(SDL_AddHintCallback$callback.class, "apply", constants$3.const$4);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_AddHintCallback",
        constants$59.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(SDL_DelHintCallback$callback.class, "apply", constants$3.const$4);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_DelHintCallback",
        constants$59.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_ClearHints",
        constants$32.const$3
    );
}


