// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$72 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$72() {}
    static final VarHandle const$0 = constants$71.const$2.varHandle(MemoryLayout.PathElement.groupElement("refresh_rate"));
    static final VarHandle const$1 = constants$71.const$2.varHandle(MemoryLayout.PathElement.groupElement("driverdata"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_GetNumVideoDrivers",
        constants$5.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_GetVideoDriver",
        constants$33.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_VideoInit",
        constants$18.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_VideoQuit",
        constants$32.const$3
    );
}


