// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$37 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$37() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(SDL_RWops.seek.class, "apply", constants$36.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$36.const$5
    );
    static final VarHandle const$2 = constants$36.const$1.varHandle(MemoryLayout.PathElement.groupElement("seek"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(SDL_RWops.read.class, "apply", constants$37.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$37.const$3
    );
}


