// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$138 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$138() {}
    static final VarHandle const$0 = constants$137.const$3.varHandle(MemoryLayout.PathElement.groupElement("which"));
    static final VarHandle const$1 = constants$137.const$3.varHandle(MemoryLayout.PathElement.groupElement("ball"));
    static final VarHandle const$2 = constants$137.const$3.varHandle(MemoryLayout.PathElement.groupElement("padding1"));
    static final VarHandle const$3 = constants$137.const$3.varHandle(MemoryLayout.PathElement.groupElement("padding2"));
    static final VarHandle const$4 = constants$137.const$3.varHandle(MemoryLayout.PathElement.groupElement("padding3"));
    static final VarHandle const$5 = constants$137.const$3.varHandle(MemoryLayout.PathElement.groupElement("xrel"));
}


