// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$35 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$35() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(SDL_RWops.write.class, "apply", constants$34.const$2);
    static final VarHandle const$1 = constants$33.const$0.varHandle(MemoryLayout.PathElement.groupElement("write"));
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(SDL_RWops.close.class, "apply", constants$18.const$4);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$18.const$4
    );
    static final VarHandle const$4 = constants$33.const$0.varHandle(MemoryLayout.PathElement.groupElement("close"));
    static final VarHandle const$5 = constants$33.const$0.varHandle(MemoryLayout.PathElement.groupElement("type"));
}


