// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$26 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$26() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_iconv_string",
        constants$26.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandleVariadic(
        "SDL_SetError",
        constants$13.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_GetError",
        constants$0.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_GetErrorMsg",
        constants$10.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.ofVoid();
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "SDL_ClearError",
        constants$26.const$5
    );
}


