// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$126 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$126() {}
    static final VarHandle const$0 = constants$125.const$3.varHandle(MemoryLayout.PathElement.groupElement("windowID"));
    static final VarHandle const$1 = constants$125.const$3.varHandle(MemoryLayout.PathElement.groupElement("state"));
    static final VarHandle const$2 = constants$125.const$3.varHandle(MemoryLayout.PathElement.groupElement("repeat"));
    static final VarHandle const$3 = constants$125.const$3.varHandle(MemoryLayout.PathElement.groupElement("padding2"));
    static final VarHandle const$4 = constants$125.const$3.varHandle(MemoryLayout.PathElement.groupElement("padding3"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("scancode"),
        JAVA_INT.withName("sym"),
        JAVA_SHORT.withName("mod"),
        MemoryLayout.paddingLayout(2),
        JAVA_INT.withName("unused")
    ).withName("SDL_Keysym");
}


