// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$169 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$169() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_SetTextureBlendMode",
        constants$49.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_GetTextureBlendMode",
        constants$6.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_SetTextureScaleMode",
        constants$49.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_GetTextureScaleMode",
        constants$6.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_SetTextureUserData",
        constants$6.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_GetTextureUserData",
        constants$6.const$0
    );
}


