// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$178 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$178() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_RenderSetClipRect",
        constants$6.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_RenderGetClipRect",
        constants$67.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_RenderIsClipEnabled",
        constants$18.const$4
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_FLOAT,
        JAVA_FLOAT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_RenderSetScale",
        constants$178.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_RenderGetScale",
        constants$59.const$0
    );
}


