// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$86 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$86() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(SDL_HitTest.class, "apply", constants$21.const$2);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$21.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(SDL_SetWindowHitTest$callback.class, "apply", constants$21.const$2);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_SetWindowHitTest",
        constants$21.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_FlashWindow",
        constants$34.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_DestroyWindow",
        constants$1.const$2
    );
}


