// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$123 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$123() {}
    static final VarHandle const$0 = constants$122.const$2.varHandle(MemoryLayout.PathElement.groupElement("event"));
    static final VarHandle const$1 = constants$122.const$2.varHandle(MemoryLayout.PathElement.groupElement("padding1"));
    static final VarHandle const$2 = constants$122.const$2.varHandle(MemoryLayout.PathElement.groupElement("padding2"));
    static final VarHandle const$3 = constants$122.const$2.varHandle(MemoryLayout.PathElement.groupElement("padding3"));
    static final VarHandle const$4 = constants$122.const$2.varHandle(MemoryLayout.PathElement.groupElement("data1"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp"),
        JAVA_INT.withName("windowID"),
        JAVA_BYTE.withName("event"),
        JAVA_BYTE.withName("padding1"),
        JAVA_BYTE.withName("padding2"),
        JAVA_BYTE.withName("padding3"),
        JAVA_INT.withName("data1"),
        JAVA_INT.withName("data2")
    ).withName("SDL_WindowEvent");
}


