// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$41 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$41() {}
    static final StructLayout const$0 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("base"),
        RuntimeHelper.POINTER.withName("here"),
        RuntimeHelper.POINTER.withName("stop")
    ).withName("");
    static final VarHandle const$1 = constants$41.const$0.varHandle(MemoryLayout.PathElement.groupElement("base"));
    static final VarHandle const$2 = constants$41.const$0.varHandle(MemoryLayout.PathElement.groupElement("here"));
    static final VarHandle const$3 = constants$41.const$0.varHandle(MemoryLayout.PathElement.groupElement("stop"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("data1"),
        RuntimeHelper.POINTER.withName("data2")
    ).withName("");
    static final VarHandle const$5 = constants$41.const$4.varHandle(MemoryLayout.PathElement.groupElement("data1"));
}


