// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$97 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$97() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_LoadBMP_RW",
        constants$15.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_SaveBMP_RW",
        constants$6.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_SetSurfaceRLE",
        constants$49.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_HasSurfaceRLE",
        constants$18.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_SetColorKey",
        constants$76.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_HasColorKey",
        constants$18.const$4
    );
}


