// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$104 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$104() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_SensorGetDataWithTimestamp",
        constants$104.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_SensorClose",
        constants$1.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_SensorUpdate",
        constants$26.const$5
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("bindType"),
        MemoryLayout.unionLayout(
            JAVA_INT.withName("button"),
            JAVA_INT.withName("axis"),
            MemoryLayout.structLayout(
                JAVA_INT.withName("hat"),
                JAVA_INT.withName("hat_mask")
            ).withName("hat")
        ).withName("value")
    ).withName("SDL_GameControllerButtonBind");
    static final VarHandle const$5 = constants$104.const$4.varHandle(MemoryLayout.PathElement.groupElement("bindType"));
}


