// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final VarHandle const$0 = constants$36.const$1.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final UnionLayout const$1 = MemoryLayout.unionLayout(
        MemoryLayout.structLayout(
            JAVA_INT.withName("append"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("h"),
            MemoryLayout.structLayout(
                RuntimeHelper.POINTER.withName("data"),
                JAVA_LONG.withName("size"),
                JAVA_LONG.withName("left")
            ).withName("buffer")
        ).withName("windowsio"),
        MemoryLayout.structLayout(
            JAVA_INT.withName("autoclose"),
            MemoryLayout.paddingLayout(4),
            RuntimeHelper.POINTER.withName("fp")
        ).withName("stdio"),
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("base"),
            RuntimeHelper.POINTER.withName("here"),
            RuntimeHelper.POINTER.withName("stop")
        ).withName("mem"),
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("data1"),
            RuntimeHelper.POINTER.withName("data2")
        ).withName("unknown")
    ).withName("");
    static final StructLayout const$2 = MemoryLayout.structLayout(
        JAVA_INT.withName("append"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("h"),
        MemoryLayout.structLayout(
            RuntimeHelper.POINTER.withName("data"),
            JAVA_LONG.withName("size"),
            JAVA_LONG.withName("left")
        ).withName("buffer")
    ).withName("");
    static final VarHandle const$3 = constants$39.const$2.varHandle(MemoryLayout.PathElement.groupElement("append"));
    static final VarHandle const$4 = constants$39.const$2.varHandle(MemoryLayout.PathElement.groupElement("h"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        RuntimeHelper.POINTER.withName("data"),
        JAVA_LONG.withName("size"),
        JAVA_LONG.withName("left")
    ).withName("");
}


