// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$62 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$62() {}
    static final VarHandle const$0 = constants$60.const$5.varHandle(MemoryLayout.PathElement.groupElement("userdata"));
    static final VarHandle const$1 = constants$60.const$5.varHandle(MemoryLayout.PathElement.groupElement("locked"));
    static final VarHandle const$2 = constants$60.const$5.varHandle(MemoryLayout.PathElement.groupElement("list_blitmap"));
    static final VarHandle const$3 = constants$60.const$5.varHandle(MemoryLayout.PathElement.groupElement("map"));
    static final VarHandle const$4 = constants$60.const$5.varHandle(MemoryLayout.PathElement.groupElement("refcount"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(SDL_blit.class, "apply", constants$5.const$3);
}


