// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$48 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$48() {}
    static final VarHandle const$0 = constants$47.const$5.varHandle(MemoryLayout.PathElement.groupElement("r"));
    static final VarHandle const$1 = constants$47.const$5.varHandle(MemoryLayout.PathElement.groupElement("g"));
    static final VarHandle const$2 = constants$47.const$5.varHandle(MemoryLayout.PathElement.groupElement("b"));
    static final VarHandle const$3 = constants$47.const$5.varHandle(MemoryLayout.PathElement.groupElement("a"));
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("ncolors"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("colors"),
        JAVA_INT.withName("version"),
        JAVA_INT.withName("refcount")
    ).withName("SDL_Palette");
    static final VarHandle const$5 = constants$48.const$4.varHandle(MemoryLayout.PathElement.groupElement("ncolors"));
}


