// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$155 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$155() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_HasEvent",
        constants$2.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_HasEvents",
        constants$59.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_FlushEvent",
        constants$58.const$5
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_FlushEvents",
        constants$155.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_PollEvent",
        constants$13.const$1
    );
}


