// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$155 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$155() {}
    static final VarHandle const$0 = constants$154.const$2.varHandle(MemoryLayout.PathElement.groupElement("gestureId"));
    static final VarHandle const$1 = constants$154.const$2.varHandle(MemoryLayout.PathElement.groupElement("numFingers"));
    static final VarHandle const$2 = constants$154.const$2.varHandle(MemoryLayout.PathElement.groupElement("error"));
    static final VarHandle const$3 = constants$154.const$2.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$4 = constants$154.const$2.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final StructLayout const$5 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp"),
        RuntimeHelper.POINTER.withName("file"),
        JAVA_INT.withName("windowID"),
        MemoryLayout.paddingLayout(4)
    ).withName("SDL_DropEvent");
}


