// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$181 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$181() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_RenderSetVSync",
        constants$49.const$3
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_BYTE.withName("ucEnableBits1"),
        JAVA_BYTE.withName("ucEnableBits2"),
        JAVA_BYTE.withName("ucRumbleRight"),
        JAVA_BYTE.withName("ucRumbleLeft"),
        JAVA_BYTE.withName("ucHeadphoneVolume"),
        JAVA_BYTE.withName("ucSpeakerVolume"),
        JAVA_BYTE.withName("ucMicrophoneVolume"),
        JAVA_BYTE.withName("ucAudioEnableBits"),
        JAVA_BYTE.withName("ucMicLightMode"),
        JAVA_BYTE.withName("ucAudioMuteBits"),
        MemoryLayout.sequenceLayout(11, JAVA_BYTE).withName("rgucRightTriggerEffect"),
        MemoryLayout.sequenceLayout(11, JAVA_BYTE).withName("rgucLeftTriggerEffect"),
        MemoryLayout.sequenceLayout(6, JAVA_BYTE).withName("rgucUnknown1"),
        JAVA_BYTE.withName("ucLedFlags"),
        MemoryLayout.sequenceLayout(2, JAVA_BYTE).withName("rgucUnknown2"),
        JAVA_BYTE.withName("ucLedAnim"),
        JAVA_BYTE.withName("ucLedBrightness"),
        JAVA_BYTE.withName("ucPadLights"),
        JAVA_BYTE.withName("ucLedRed"),
        JAVA_BYTE.withName("ucLedGreen"),
        JAVA_BYTE.withName("ucLedBlue")
    ).withName("DS5EffectsState_t");
    static final VarHandle const$2 = constants$181.const$1.varHandle(MemoryLayout.PathElement.groupElement("ucEnableBits1"));
    static final VarHandle const$3 = constants$181.const$1.varHandle(MemoryLayout.PathElement.groupElement("ucEnableBits2"));
    static final VarHandle const$4 = constants$181.const$1.varHandle(MemoryLayout.PathElement.groupElement("ucRumbleRight"));
    static final VarHandle const$5 = constants$181.const$1.varHandle(MemoryLayout.PathElement.groupElement("ucRumbleLeft"));
}


