// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$153 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$153() {}
    static final VarHandle const$0 = constants$152.const$2.varHandle(MemoryLayout.PathElement.groupElement("code"));
    static final VarHandle const$1 = constants$152.const$2.varHandle(MemoryLayout.PathElement.groupElement("data1"));
    static final VarHandle const$2 = constants$152.const$2.varHandle(MemoryLayout.PathElement.groupElement("data2"));
    static final StructLayout const$3 = MemoryLayout.structLayout(
        JAVA_INT.withName("type"),
        JAVA_INT.withName("timestamp"),
        RuntimeHelper.POINTER.withName("msg")
    ).withName("SDL_SysWMEvent");
    static final VarHandle const$4 = constants$153.const$3.varHandle(MemoryLayout.PathElement.groupElement("type"));
    static final VarHandle const$5 = constants$153.const$3.varHandle(MemoryLayout.PathElement.groupElement("timestamp"));
}


