// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$82 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$82() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_GetRelativeMouseState",
        constants$8.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_WarpMouseInWindow",
        constants$66.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_WarpMouseGlobal",
        constants$59.const$1
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_SetRelativeMouseMode",
        constants$2.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_CaptureMouse",
        constants$2.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_GetRelativeMouseMode",
        constants$1.const$4
    );
}


