// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$128 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$128() {}
    static final VarHandle const$0 = constants$127.const$4.varHandle(MemoryLayout.PathElement.groupElement("timestamp"));
    static final VarHandle const$1 = constants$127.const$4.varHandle(MemoryLayout.PathElement.groupElement("windowID"));
    static final VarHandle const$2 = constants$127.const$4.varHandle(MemoryLayout.PathElement.groupElement("which"));
    static final VarHandle const$3 = constants$127.const$4.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$4 = constants$127.const$4.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$5 = constants$127.const$4.varHandle(MemoryLayout.PathElement.groupElement("direction"));
}


