// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$117 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$117() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_SetWindowModalFor",
        constants$6.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_SetWindowInputFocus",
        constants$18.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_SetWindowGammaRamp",
        constants$5.const$3
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_GetWindowGammaRamp",
        constants$5.const$3
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(SDL_HitTest.class, "apply", constants$21.const$2);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$21.const$2
    );
}


