// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$180 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$180() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_SetRenderDrawBlendMode",
        constants$34.const$3
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_GetRenderDrawBlendMode",
        constants$6.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_RenderClear",
        constants$18.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_RenderDrawPoint",
        constants$65.const$4
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_RenderDrawPoints",
        constants$6.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_RenderDrawLine",
        constants$164.const$0
    );
}


