// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$70 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$70() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_SetWindowFullscreen",
        constants$28.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_HasWindowSurface",
        constants$13.const$1
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_GetWindowSurface",
        constants$2.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_UpdateWindowSurface",
        constants$13.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_UpdateWindowSurfaceRects",
        constants$2.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_DestroyWindowSurface",
        constants$13.const$1
    );
}


