// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$57 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$57() {}
    static final MethodHandle const$0 = RuntimeHelper.upcallHandle(SDL_VirtualJoystickDesc.SetPlayerIndex.class, "apply", constants$56.const$5);
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        constants$56.const$5
    );
    static final VarHandle const$2 = constants$54.const$2.varHandle(MemoryLayout.PathElement.groupElement("SetPlayerIndex"));
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_SHORT,
        JAVA_SHORT
    );
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(SDL_VirtualJoystickDesc.Rumble.class, "apply", constants$57.const$3);
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        constants$57.const$3
    );
}


