// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$101 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$101() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_SHORT,
        JAVA_SHORT
    );
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(SDL_VirtualJoystickDesc.Rumble.class, "apply", constants$101.const$0);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$101.const$0
    );
    static final VarHandle const$3 = constants$98.const$0.varHandle(MemoryLayout.PathElement.groupElement("Rumble"));
    static final MethodHandle const$4 = RuntimeHelper.upcallHandle(SDL_VirtualJoystickDesc.RumbleTriggers.class, "apply", constants$101.const$0);
    static final VarHandle const$5 = constants$98.const$0.varHandle(MemoryLayout.PathElement.groupElement("RumbleTriggers"));
}


