// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$164 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$164() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "SDL_RenderSetLogicalSize",
        constants$54.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_RenderGetLogicalSize",
        constants$47.const$4
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_RenderSetIntegerScale",
        constants$28.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "SDL_RenderGetIntegerScale",
        constants$13.const$1
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_RenderSetViewport",
        constants$8.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_RenderGetViewport",
        constants$56.const$0
    );
}


