// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$40 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$40() {}
    static final VarHandle const$0 = constants$38.const$0.varHandle(MemoryLayout.PathElement.groupElement("Aloss"));
    static final VarHandle const$1 = constants$38.const$0.varHandle(MemoryLayout.PathElement.groupElement("Rshift"));
    static final VarHandle const$2 = constants$38.const$0.varHandle(MemoryLayout.PathElement.groupElement("Gshift"));
    static final VarHandle const$3 = constants$38.const$0.varHandle(MemoryLayout.PathElement.groupElement("Bshift"));
    static final VarHandle const$4 = constants$38.const$0.varHandle(MemoryLayout.PathElement.groupElement("Ashift"));
    static final VarHandle const$5 = constants$38.const$0.varHandle(MemoryLayout.PathElement.groupElement("refcount"));
}


