// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct SDL_Keysym {
 *     enum SDL_Scancode scancode;
 *     int sym;
 *     unsigned short mod;
 *     unsigned int unused;
 * };
 * }
 */
public class SDL_Keysym {

    public static MemoryLayout $LAYOUT() {
        return constants$90.const$1;
    }
    public static VarHandle scancode$VH() {
        return constants$90.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enum SDL_Scancode scancode;
     * }
     */
    public static int scancode$get(MemorySegment seg) {
        return (int)constants$90.const$2.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enum SDL_Scancode scancode;
     * }
     */
    public static void scancode$set(MemorySegment seg, int x) {
        constants$90.const$2.set(seg, x);
    }
    public static int scancode$get(MemorySegment seg, long index) {
        return (int)constants$90.const$2.get(seg.asSlice(index*sizeof()));
    }
    public static void scancode$set(MemorySegment seg, long index, int x) {
        constants$90.const$2.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle sym$VH() {
        return constants$90.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int sym;
     * }
     */
    public static int sym$get(MemorySegment seg) {
        return (int)constants$90.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int sym;
     * }
     */
    public static void sym$set(MemorySegment seg, int x) {
        constants$90.const$3.set(seg, x);
    }
    public static int sym$get(MemorySegment seg, long index) {
        return (int)constants$90.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void sym$set(MemorySegment seg, long index, int x) {
        constants$90.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle mod$VH() {
        return constants$90.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned short mod;
     * }
     */
    public static short mod$get(MemorySegment seg) {
        return (short)constants$90.const$4.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned short mod;
     * }
     */
    public static void mod$set(MemorySegment seg, short x) {
        constants$90.const$4.set(seg, x);
    }
    public static short mod$get(MemorySegment seg, long index) {
        return (short)constants$90.const$4.get(seg.asSlice(index*sizeof()));
    }
    public static void mod$set(MemorySegment seg, long index, short x) {
        constants$90.const$4.set(seg.asSlice(index*sizeof()), x);
    }
    public static VarHandle unused$VH() {
        return constants$90.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int unused;
     * }
     */
    public static int unused$get(MemorySegment seg) {
        return (int)constants$90.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int unused;
     * }
     */
    public static void unused$set(MemorySegment seg, int x) {
        constants$90.const$5.set(seg, x);
    }
    public static int unused$get(MemorySegment seg, long index) {
        return (int)constants$90.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void unused$set(MemorySegment seg, long index, int x) {
        constants$90.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


