// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct SDL_ControllerTouchpadEvent {
 *     unsigned int type;
 *     unsigned int timestamp;
 *     int which;
 *     int touchpad;
 *     int finger;
 *     float x;
 *     float y;
 *     float pressure;
 * };
 * }
 */
public class SDL_ControllerTouchpadEvent {

    public static MemoryLayout $LAYOUT() {
        return constants$140.const$5;
    }
    public static VarHandle type$VH() {
        return constants$141.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int type;
     * }
     */
    public static int type$get(MemorySegment seg) {
        return (int)constants$141.const$0.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int type;
     * }
     */
    public static void type$set(MemorySegment seg, int x) {
        constants$141.const$0.set(seg, 0L, x);
    }
    public static int type$get(MemorySegment seg, long index) {
        return (int)constants$141.const$0.get(seg, index * sizeof());    }
    public static void type$set(MemorySegment seg, long index, int x) {
        constants$141.const$0.set(seg, index * sizeof(), x);
    }
    public static VarHandle timestamp$VH() {
        return constants$141.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * unsigned int timestamp;
     * }
     */
    public static int timestamp$get(MemorySegment seg) {
        return (int)constants$141.const$1.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * unsigned int timestamp;
     * }
     */
    public static void timestamp$set(MemorySegment seg, int x) {
        constants$141.const$1.set(seg, 0L, x);
    }
    public static int timestamp$get(MemorySegment seg, long index) {
        return (int)constants$141.const$1.get(seg, index * sizeof());    }
    public static void timestamp$set(MemorySegment seg, long index, int x) {
        constants$141.const$1.set(seg, index * sizeof(), x);
    }
    public static VarHandle which$VH() {
        return constants$141.const$2;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int which;
     * }
     */
    public static int which$get(MemorySegment seg) {
        return (int)constants$141.const$2.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int which;
     * }
     */
    public static void which$set(MemorySegment seg, int x) {
        constants$141.const$2.set(seg, 0L, x);
    }
    public static int which$get(MemorySegment seg, long index) {
        return (int)constants$141.const$2.get(seg, index * sizeof());    }
    public static void which$set(MemorySegment seg, long index, int x) {
        constants$141.const$2.set(seg, index * sizeof(), x);
    }
    public static VarHandle touchpad$VH() {
        return constants$141.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int touchpad;
     * }
     */
    public static int touchpad$get(MemorySegment seg) {
        return (int)constants$141.const$3.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int touchpad;
     * }
     */
    public static void touchpad$set(MemorySegment seg, int x) {
        constants$141.const$3.set(seg, 0L, x);
    }
    public static int touchpad$get(MemorySegment seg, long index) {
        return (int)constants$141.const$3.get(seg, index * sizeof());    }
    public static void touchpad$set(MemorySegment seg, long index, int x) {
        constants$141.const$3.set(seg, index * sizeof(), x);
    }
    public static VarHandle finger$VH() {
        return constants$141.const$4;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int finger;
     * }
     */
    public static int finger$get(MemorySegment seg) {
        return (int)constants$141.const$4.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int finger;
     * }
     */
    public static void finger$set(MemorySegment seg, int x) {
        constants$141.const$4.set(seg, 0L, x);
    }
    public static int finger$get(MemorySegment seg, long index) {
        return (int)constants$141.const$4.get(seg, index * sizeof());    }
    public static void finger$set(MemorySegment seg, long index, int x) {
        constants$141.const$4.set(seg, index * sizeof(), x);
    }
    public static VarHandle x$VH() {
        return constants$141.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float x;
     * }
     */
    public static float x$get(MemorySegment seg) {
        return (float)constants$141.const$5.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float x;
     * }
     */
    public static void x$set(MemorySegment seg, float x) {
        constants$141.const$5.set(seg, 0L, x);
    }
    public static float x$get(MemorySegment seg, long index) {
        return (float)constants$141.const$5.get(seg, index * sizeof());    }
    public static void x$set(MemorySegment seg, long index, float x) {
        constants$141.const$5.set(seg, index * sizeof(), x);
    }
    public static VarHandle y$VH() {
        return constants$142.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float y;
     * }
     */
    public static float y$get(MemorySegment seg) {
        return (float)constants$142.const$0.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float y;
     * }
     */
    public static void y$set(MemorySegment seg, float x) {
        constants$142.const$0.set(seg, 0L, x);
    }
    public static float y$get(MemorySegment seg, long index) {
        return (float)constants$142.const$0.get(seg, index * sizeof());    }
    public static void y$set(MemorySegment seg, long index, float x) {
        constants$142.const$0.set(seg, index * sizeof(), x);
    }
    public static VarHandle pressure$VH() {
        return constants$142.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * float pressure;
     * }
     */
    public static float pressure$get(MemorySegment seg) {
        return (float)constants$142.const$1.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * float pressure;
     * }
     */
    public static void pressure$set(MemorySegment seg, float x) {
        constants$142.const$1.set(seg, 0L, x);
    }
    public static float pressure$get(MemorySegment seg, long index) {
        return (float)constants$142.const$1.get(seg, index * sizeof());    }
    public static void pressure$set(MemorySegment seg, long index, float x) {
        constants$142.const$1.set(seg, index * sizeof(), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


