// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * void* (*SDL_GetOriginalMemoryFunctions$calloc_func)(unsigned long long,unsigned long long);
 * }
 */
public interface SDL_GetOriginalMemoryFunctions$calloc_func {

    java.lang.foreign.MemorySegment apply(long nmemb, long size);
    static MemorySegment allocate(SDL_GetOriginalMemoryFunctions$calloc_func fi, Arena scope) {
        return RuntimeHelper.upcallStub(constants$3.const$1, fi, constants$0.const$4, scope);
    }
    static SDL_GetOriginalMemoryFunctions$calloc_func ofAddress(MemorySegment addr, Arena arena) {
        MemorySegment symbol = addr.reinterpret(arena, null);
        return (long _nmemb, long _size) -> {
            try {
                return (java.lang.foreign.MemorySegment)constants$2.const$1.invokeExact(symbol, _nmemb, _size);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


