// Generated by jextract

package sdl.jextract;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct SDL_Point {
 *     int x;
 *     int y;
 * };
 * }
 */
public class SDL_Point {

    public static MemoryLayout $LAYOUT() {
        return constants$44.const$4;
    }
    public static VarHandle x$VH() {
        return constants$44.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int x;
     * }
     */
    public static int x$get(MemorySegment seg) {
        return (int)constants$44.const$5.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int x;
     * }
     */
    public static void x$set(MemorySegment seg, int x) {
        constants$44.const$5.set(seg, 0L, x);
    }
    public static int x$get(MemorySegment seg, long index) {
        return (int)constants$44.const$5.get(seg, index * sizeof());    }
    public static void x$set(MemorySegment seg, long index, int x) {
        constants$44.const$5.set(seg, index * sizeof(), x);
    }
    public static VarHandle y$VH() {
        return constants$45.const$0;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int y;
     * }
     */
    public static int y$get(MemorySegment seg) {
        return (int)constants$45.const$0.get(seg, 0L);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int y;
     * }
     */
    public static void y$set(MemorySegment seg, int x) {
        constants$45.const$0.set(seg, 0L, x);
    }
    public static int y$get(MemorySegment seg, long index) {
        return (int)constants$45.const$0.get(seg, index * sizeof());    }
    public static void y$set(MemorySegment seg, long index, int x) {
        constants$45.const$0.set(seg, index * sizeof(), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


