// Generated by jextract

package sdl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$122 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$122() {}
    static final VarHandle const$0 = constants$121.const$5.varHandle(MemoryLayout.PathElement.groupElement("ucEnableBits1"));
    static final VarHandle const$1 = constants$121.const$5.varHandle(MemoryLayout.PathElement.groupElement("ucEnableBits2"));
    static final VarHandle const$2 = constants$121.const$5.varHandle(MemoryLayout.PathElement.groupElement("ucRumbleRight"));
    static final VarHandle const$3 = constants$121.const$5.varHandle(MemoryLayout.PathElement.groupElement("ucRumbleLeft"));
    static final VarHandle const$4 = constants$121.const$5.varHandle(MemoryLayout.PathElement.groupElement("ucHeadphoneVolume"));
    static final VarHandle const$5 = constants$121.const$5.varHandle(MemoryLayout.PathElement.groupElement("ucSpeakerVolume"));
}


