// Generated by jextract

package sdl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$82 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$82() {}
    static final VarHandle const$0 = constants$81.const$2.varHandle(MemoryLayout.PathElement.groupElement("BytesPerPixel"));
    static final VarHandle const$1 = constants$81.const$2.varHandle(MemoryLayout.PathElement.groupElement("Rmask"));
    static final VarHandle const$2 = constants$81.const$2.varHandle(MemoryLayout.PathElement.groupElement("Gmask"));
    static final VarHandle const$3 = constants$81.const$2.varHandle(MemoryLayout.PathElement.groupElement("Bmask"));
    static final VarHandle const$4 = constants$81.const$2.varHandle(MemoryLayout.PathElement.groupElement("Amask"));
    static final VarHandle const$5 = constants$81.const$2.varHandle(MemoryLayout.PathElement.groupElement("Rloss"));
}


