// Generated by jextract

package sdl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$90 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$90() {}
    static final VarHandle const$0 = constants$89.const$5.varHandle(MemoryLayout.PathElement.groupElement("x"));
    static final VarHandle const$1 = constants$89.const$5.varHandle(MemoryLayout.PathElement.groupElement("y"));
    static final VarHandle const$2 = constants$89.const$5.varHandle(MemoryLayout.PathElement.groupElement("w"));
    static final VarHandle const$3 = constants$89.const$5.varHandle(MemoryLayout.PathElement.groupElement("h"));
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_HasIntersection",
        constants$6.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_IntersectRect",
        constants$21.const$2
    );
}


