// Generated by jextract

package sdl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$59 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$59() {}
    static final VarHandle const$0 = constants$54.const$2.varHandle(MemoryLayout.PathElement.groupElement("SetLED"));
    static final MethodHandle const$1 = RuntimeHelper.upcallHandle(SDL_VirtualJoystickDesc.SendEffect.class, "apply", constants$6.const$2);
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        constants$6.const$2
    );
    static final VarHandle const$3 = constants$54.const$2.varHandle(MemoryLayout.PathElement.groupElement("SendEffect"));
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_JoystickAttachVirtualEx",
        constants$18.const$4
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_JoystickDetachVirtual",
        constants$8.const$0
    );
}


