// Generated by jextract

package sdl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$124 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$124() {}
    static final VarHandle const$0 = constants$121.const$5.varHandle(MemoryLayout.PathElement.groupElement("ucLedBrightness"));
    static final VarHandle const$1 = constants$121.const$5.varHandle(MemoryLayout.PathElement.groupElement("ucPadLights"));
    static final VarHandle const$2 = constants$121.const$5.varHandle(MemoryLayout.PathElement.groupElement("ucLedRed"));
    static final VarHandle const$3 = constants$121.const$5.varHandle(MemoryLayout.PathElement.groupElement("ucLedGreen"));
    static final VarHandle const$4 = constants$121.const$5.varHandle(MemoryLayout.PathElement.groupElement("ucLedBlue"));
    static final MemorySegment const$5 = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("I64d");
}


