// Generated by jextract

package sdl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$32 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$32() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandleVariadic(
        "SDL_SetError",
        constants$18.const$4
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "SDL_GetError",
        constants$0.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "SDL_GetErrorMsg",
        constants$15.const$4
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.ofVoid();
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "SDL_ClearError",
        constants$32.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "SDL_Error",
        constants$8.const$0
    );
}


