// Generated by jextract

package sdl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$34 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$34() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$33.const$4
    );
    static final VarHandle const$1 = constants$33.const$0.varHandle(MemoryLayout.PathElement.groupElement("seek"));
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_LONG,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG,
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(SDL_RWops.read.class, "apply", constants$34.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$34.const$2
    );
    static final VarHandle const$5 = constants$33.const$0.varHandle(MemoryLayout.PathElement.groupElement("read"));
}


