// Generated by jextract

package sdl;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * typedef struct SDL_semaphore SDL_sem;
 * }
 */
public final class SDL_sem {

    // Suppresses default constructor, ensuring non-instantiability.
    private SDL_sem() {}
}


